# Simpris docker 

version: '3'

services:
  web:
    restart: always
    build: .
    command: "gunicorn --timeout=30 --workers=2 --bind :8000 simpris.wsgi:application"
    volumes:
      - .:/code
      - .:/uploads
      - ./static:/code/static
    ports:
      - "8000:8000"
    env_file:
      - docker-dev.env 
    networks:
      - web_network

  nginx:
    image: nginx:latest
    ports:
      - "3000:8000"
      - 80:80
      - 443:443
    volumes:
      - ./static:/code/static
      - ./config/nginx:/etc/nginx/conf.d
      - ./certs/dev:/certs
    depends_on:
      - web
    networks:
      - web_network

networks:
  web_network:
    driver: bridge               