# Generated by Django 2.1.1 on 2019-03-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='documentfilename',
            field=models.CharField(db_column='documentfilename', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='documenttitle',
            field=models.CharField(blank=True, db_column='documenttitle', max_length=100, null=True),
        ),
    ]
