CREATE TABLE `problem` (
  `problemID` int(11) NOT NULL AUTO_INCREMENT,
  `clientID` int(11) NOT NULL,
  `organisationID` int(11) NOT NULL,
  `problemTypeID` int(11) NOT NULL,
  `problemSubTypeID` int(11) DEFAULT NULL,
  `problemHeader` varchar(50) NOT NULL,
  `problemDescription` varchar(2000) NOT NULL,
  `noOfPeopleAffected` int(11) NOT NULL,
  `scope` int(11) NOT NULL,
  `problemStatusID` int(11) DEFAULT NULL,
  `problemPriorityID` int(11) DEFAULT NULL,
  `queueid` int(11) DEFAULT NULL,
  `assignedTo` int(11) DEFAULT NULL,
  `completedDate` datetime DEFAULT NULL,
  `createdDate` datetime NOT NULL,
  `createdBy` int(11) NOT NULL,
  `updatedDate` datetime DEFAULT NULL,
  `updatedBy` int(11) DEFAULT NULL,
  `deletedDate` datetime DEFAULT NULL,
  `deletedBy` int(11) DEFAULT NULL,
  PRIMARY KEY (`problemID`),
  UNIQUE KEY `ix_problem` (`organisationID`,`problemHeader`),
  KEY `FK_problem_organisation` (`organisationID`),
  KEY `ix_problem_client` (`clientID`),
  KEY `ix_problem_type` (`problemTypeID`),
  CONSTRAINT `FK_problem_organisation` FOREIGN KEY (`organisationID`) REFERENCES `organisation` (`organisationID`)
)